name: twitch
description: Twitch-like live streaming app with a custom neon+glass UI
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  video_player: ^2.9.1
  shimmer: ^3.0.0
  agora_rtc_ng: ^6.0.0-beta.2

  # ðŸ”¥ Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  firebase_messaging: ^16.0.0
  permission_handler: ^12.0.1
  agora_rtc_engine: ^6.5.2
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
